<?php
/**
 * Steam Calculators
 *
 * @package    View_Scripts
 * @version    beta
 * @author     Michael B Muller
 * <mbm@analyticalenergy.com> 
 */
?>
<h1><?php echo $this->translator->_('About the Steam Calculators');?></h1>

<p><?php echo $this->translator->_('The Steam Calculators provide a variety of steam related calculations and models with comprehensive calculation descriptions and details.');?></p>
<h2><?php echo $this->translator->_('User Data Not Specifically Recorded by Steam Calculators');?></h2>
<p><?php echo $this->translator->_('Any user data entered into the Steam Calculators is only saved for a specific browser session. Close the browser and all data is deleted. None of Steam Calculators specifically record, maintain, or otherwise profile user data.');?></p>
<p><?php echo $this->translator->_('For EERE Web Site Policies see');?>: <a href="http://www1.eere.energy.gov/webpolicies/">http://www1.eere.energy.gov/webpolicies/</a></p>
<h2><?php echo $this->translator->_('Development Details');?></h2>
<p><?php echo $this->translator->_('All of Steam Calculators are part of a single standalone web-based application developed in PHP using support software libraries');?>:</p>
<ul>
    <li>PHP [<a href="http://en.wikipedia.org/wiki/PHP"><?php echo $this->translator->_('link');?></a>]</li>
    <li>Zend Framework [<a href="http://framework.zend.com/"><?php echo $this->translator->_('link');?></a>]:  <?php echo $this->translator->_('An open source, object-oriented web application framework');?></li>
    <li>PHPExcel [<a href="http://phpexcel.codeplex.com/"><?php echo $this->translator->_('link');?></a>]: <?php echo $this->translator->_('A spreadsheet engine capability of reading, writing and creating Excel and OpenXML documents in PHP');?></li>
</ul>
<p><?php echo $this->translator->_('To enhance user interactions, the calculators also extensively use JavaScript and the following JavaScript Libraries');?>:</p>
<ul>
    <li>JavaScript [<a href="http://en.wikipedia.org/wiki/JavaScript"><?php echo $this->translator->_('link');?></a>]</li>
    <li>jQuery [<a href="http://jquery.com/"><?php echo $this->translator->_('link');?></a>]: <?php echo $this->translator->_('A multi-browser JavaScript library');?></li>
    <li>jQuery UI [<a href="http://jqueryui.com/"><?php echo $this->translator->_('link');?></a>]: <?php echo $this->translator->_('Provides abstractions for low-level interaction and animation');?></li>
</ul>
<p><?php echo $this->translator->_('The Steam Calculators were developed by Michael B Muller for the U.S. Department of Energy and Oak Ridge National Labs.');?></p>

<h2><?php echo $this->translator->_('Steam Properties');?></h2>
<p><?php echo $this->translator->_('The Steam Calculators calculate all steam properties using the International Association for the Properties of Water and Steam\'s Thermodynamic Properties of Water and Steam Industrial Formulation');?>, IAPWS-IF97, 2007, <a href="http://www.iapws.org/">www.iapws.org</a></p>


