<?php
/**
 * Steam Calculators
 *
 * @package    View_Scripts
 * @subpackage Steam Model
 * @version    beta
 * @author     Michael B Muller
 * <mbm@analyticalenergy.com>
 * 
 */

echo $this->partial('index/partials/modelMenu.phtml', array('action' => 'baseEnergy'));
?>
<h2><?php echo $this->translator->_('Base Energy Flows');?></h2>
<div style="position: relative;  float: left; width: 700px; height: 450px; font-size: .75em">
    <?php echo Steam_Model_Sankey::addSankeyText($this->sMc->baseModel); ?>
    <img src="baseSankey" alt="Base Model Sankey">
</div>
