<?php
/**
 * Steam Calculators
 *
 * @package    View_Scripts
 * @version    beta
 * @author     Michael B Muller
 * <mbm@analyticalenergy.com> 
 */

?>
<h1><?php echo $this->translator->_('Steam Resources');?></h1>
<BR>
<h2><?php echo $this->translator->_('SSMT Guide');?></h2>
<p><?php echo $this->translator->_("This document is designed to be used as both a comprehensive presentation band a quick reference for the Steam System Modeling Tool (SSMT)");?></p>
<ul>
    <li><?php echo $this->translator->_('SSMT Guide');?>: <a href="SSMTGuide.pdf">download PDF</a></li>
</ul>

<BR>
<h2><?php echo $this->translator->_('Advanced Manufacturing Office: Technical Steam Resources');?></h2>
<ul>
    <li><?php echo $this->translator->_('Steam Resources Overview');?>: <a href="http://www1.eere.energy.gov/manufacturing/tech_deployment/steam.html">link</a></li>
    <li><?php echo $this->translator->_('Steam Sourcebook for Industry, Oct 2012');?>: <a href="http://www1.eere.energy.gov/manufacturing/tech_deployment/pdfs/steamsourcebook.pdf">PDF</a>
        <ul>
            <li><?php echo $this->translator->_('Directory of Contacts');?>: <a href="http://www1.eere.energy.gov/manufacturing/tech_deployment/pdfs/steamsourcebook.pdf#page=41">PDF</a></li>
        </ul>
    </li>
</ul>
<br>

<h2><?php echo $this->translator->_('Steam Property Calculations');?></h2>
<p><?php echo $this->translator->_("The Steam Calculators calculate all steam properties using the International Association for the Properties of Water and Steam's Thermodynamic Properties of Water and Steam Industrial Formulation, IAPWS-IF97, 2007");?></p>
<ul>
    <li><?php echo $this->translator->_('IAPWS Website');?>: <a href="http://www.iapws.org/">www.iapws.org</a></li>
    <li><?php echo $this->translator->_('IAPWS-IF97');?>: <a href="http://www.iapws.org/relguide/IF97-Rev.pdf">PDF</a></li>
</ul>