<?php
/**
 * Steam Calculators
 *
 * @package    View_Scripts
 * @version    beta
 * @author     Michael B Muller
 * <mbm@analyticalenergy.com> 
 */
?>
<p><a href="http://www.eere.energy.gov/manufacturing/contacts.html">Contacts</a> |  <a href="http://www.eere.energy.gov/webpolicies/"><?php echo $this->translator->_("Web Site Policies");?></a>
    | <a href="http://www.energy.gov/">U.S. Department of Energy</a> | <a href="http://www.usa.gov/">USA.gov</a><br>
    
	Version: <?php echo TOOL_VERSION;?> - Build Date: <?php echo TOOL_BUILD_DATE;?></p>

